
export const TOP_MUSIC_LIST_STARTED = 'TOP_MUSIC_LIST_STARTED';
export const TOP_MUSIC_LIST_SUCCESS = 'TOP_MUSIC_LIST_SUCCESS';
export const TOP_MUSIC_LIST_ERROR = 'TOP_MUSIC_LIST_ERROR';


export const CURRENT_MUSIC_LIST = 'CURRENT_MUSIC_LIST';